if (FALSE) {
  # Use this to install required packages
  install.packages("this.path")
  install.packages("R.utils")
  install.packages("data.table")
  install.packages("rsvd")
  install.packages("Rtsne")
  install.packages("cowplot")
  if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::install("SingleCellExperiment")
  BiocManager::install("scater")
  install.packages("ggplot2")
  install.packages("corrplot")
  install.packages("doParallel")
}
library("this.path")
library("R.utils")
library("data.table")
library("rsvd")
library("Rtsne")
library("cowplot")
library("ggplot2")
library("corrplot")
library("doParallel")

